### ISSUE TITLE
Escrever o roteiro do segundo capitulo

### ISSUE THREAD

**Issue by 3ndri0** [3ndri0/historia-em-quadrinhos---pt2#15]
Com base no resultado da issue "Criar o esboço geral da história" realizada na sprint 01 deve ser gerado o roteiro do segundo capitulo;

**Comment by RafaelCapeletti** [comment]
Roteiro Segundo Capítulo:

Rai luta para se desconectar dos cabos de dados, finalmente conseguindo romper o último elo que o mantém aprisionado. O sistema ao redor reage, disparando alertas sobre a desconexão inesperada.
Ao perceber sua liberdade, Rai se move pelo prédio em um misto de confusão e urgência. Alarmes soam, e as forças de segurança da NeoCorp entram em ação, mobilizando drones e guardas robóticos. Rai encontra um terminal desativado e, guiado por uma voz misteriosa (Lambda), descobre passagens secretas que o ajudam a despistar temporariamente os guardas. Lambda o orienta pelos corredores e sistemas de ventilação, aproveitando as vulnerabilidades do sistema de segurança. A ação é frenética, e Rai mal escapa de ser capturado por unidades de segurança que chegam a poucos passos de onde ele estava.
