### ISSUE TITLE
Criar o esboço geral da história

### ISSUE THREAD

**Issue by juniorbohry** [3ndri0/historia-em-quadrinhos---pt2#2]
A criação do esboço geral da história deve seguir os seguintes elementos:

Contexto : Em uma megacidade controlada pela corporação NeoCorp, nanomáquinas implantadas em nossos cidadãos monitoram e controlam suas emoções e comportamentos, criando uma sociedade manipulada e sem rebeldia.

Protagonista : Rai, um jovem que descobre uma falha no sistema de nanomáquinas, se liberta do controle da NeoCorp. Com o auxílio da IA ​​clandestina Lambda, ele busca expor a verdade e romper a corporação.

Conflito principal : A NeoCorp está desenvolvendo uma nova tecnologia capaz de apagar memórias e reprogramar mentes, tornando a luta de Rai uma corrida contra o tempo para salvar a identidade humana e preservar sua própria liberdade.

**Comment by RafaelCapeletti** [comment]
Esboço geral da história, organizado em três atos principais para estruturar a narrativa.

**Ato I: O Despertar**
Num futuro próximo, a humanidade está confinada em uma imensa megacidade controlada pela poderosa corporação de tecnologia NeoCorp. Esta organização implantou nanomáquinas em todos os cidadãos para monitorar e controlar suas emoções e comportamentos, criando uma sociedade aparentemente importada, mas totalmente manipulada. Qualquer traço de rebeldia ou pensamento dissidente é rapidamente corrigido pela tecnologia invasiva, garantindo que a população siga obedientemente as diretrizes impostas.

A história segue Rai, um jovem que, como todos os outros, vive sob o controle invisível da NeoCorp. Ele leva uma vida rotineira e conformada, sem saber que suas emoções são constantemente reguladas. No entanto, aos poucos, Rai começa a perceber lapsos estranhos nos efeitos das nanomáquinas em seu corpo. Ele experimenta momentos de emoções intensas e pensamento crítico que escapam ao controle da corporação. Inicialmente, ele tenta ignorar essas sensações, mas não consegue evitar a sensação crescente de que algo está profundamente errado com o mundo em que vive.

Eventualmente, Rai descobriu que uma falha nas nanomáquinas implantadas em seu corpo o libertou parcialmente do controle da NeoCorp. Ele começa a recuperar sua liberdade emocional e intelectual, tornando-se um alvo em potencial para as forças de segurança da corporação. Nesse momento de vulnerabilidade, Rai é ​​contatado pela Lambda, uma inteligência artificial clandestina que existe fora dos sistemas de controle da NeoCorp. Lambda revela que essa falha é rara, mas crucial, e que Rai pode ser a chave para derrubar a corporação e libertar a humanidade do controle tecnológico.

**Ato II: A Rebelião**
Agora consciente de sua liberdade parcial, Rai é ​​solicitado a fugir, pois sabe que, assim como foi detectado, a NeoCorp tentará "corrigi-lo" ou neutralizá-lo. Com a ajuda de Lambda, ele começa a explorar áreas esquecidas da cidade, onde pequenos grupos de resistência se escondem, tentando se manter longe do radar da corporação. Ao se unir a esses rebeldes, Rai descobre a extensão do controle que a NeoCorp exerce sobre a população e a existência de outros que também escaparam, de forma limitada, das nanomáquinas.

Conforme Rai e Lambda trabalham juntos, ele aprende mais sobre o sistema de monitoramento da NeoCorp e suas vulnerabilidades. A inteligência artificial clandestina revela um plano mais sinistro da corporação: o desenvolvimento de uma nova geração de nanomáquinas, capazes não só de controlar emoções, mas também de apagar memórias e reprogramar completamente as mentes das pessoas. Isso representaria um ponto sem retorno, transformando os cidadãos em verdadeiros autômatos, sem a menor consciência de sua própria identidade ou liberdade.

A urgência da situação força Rai a agir rapidamente. Ele se torna um líder improvisado, conduzindo ataques para expor a verdade sobre a NeoCorp ao público, enquanto busca uma maneira de destruir o núcleo central que controla as nanomáquinas. No entanto, ele enfrenta desafios cada vez maiores, à medida que a corporação intensifica sua caçada por ele, utilizando sua tecnologia para rastrear cada movimento.

**Ato III: A Corrida Contra o Tempo**
No final, Rai descobre que a NeoCorp já começou a testar sua nova tecnologia em certas áreas da cidade, reprogramando completamente as mentes de alguns cidadãos para eliminar qualquer vestígio de rebeldia. Ele percebe que sua luta não é mais apenas para expor a verdade, mas também para impedir que a humanidade perca completamente sua identidade e liberdade. Com o tempo se esgotando, Rai e Lambda lançam um ataque desesperado para destruir a infraestrutura da corporação antes que uma nova geração de nanomáquinas seja implantada em massa.

Enquanto Rai enfrenta os perigos de uma sociedade completamente vigiada e controlada, ele também deve lutar contra seus próprios medos. A pressão de salvar não apenas os outros, mas também de evitar que ele próprio seja reprogramado, coloca em risco sua sanidade e determinação. No clímax da história, Rai se infiltra no centro de controle da NeoCorp, onde a última batalha pela liberdade da humanidade ocorre.

No final, a história deixa uma reflexão sobre os limites entre liberdade e controle, e até onde a tecnologia pode ir para moldar as sociedades humanas. Rai, apesar de vitorioso, descobre que a luta pela liberdade nunca realmente termina.

**Comment by RafaelCapeletti** [comment]
Esboço geral da história, organizado em três atos principais para estruturar a narrativa.

**Ato I: O Despertar**
Em um futuro próximo, a humanidade está confinada em uma imensa megacidade controlada pela poderosa corporação de tecnologia NeoCorp. Esta organização implantou nanomáquinas em todos os cidadãos para monitorar e controlar suas emoções e comportamentos, criando uma sociedade aparentemente pacífica, mas totalmente manipulada. Qualquer traço de rebeldia ou pensamento dissidente é rapidamente corrigido pela tecnologia invasiva, garantindo que a população siga obedientemente as diretrizes impostas.

A história segue Rai, um jovem que, como todos os outros, vive sob o controle invisível de NeoCorp. Ele leva uma vida rotineira e conformada, sem saber que suas emoções são constantemente reguladas. No entanto, aos poucos, Rai começa a perceber estranhos lapsos nos efeitos das nanomáquinas em seu corpo. Ele experimenta momentos de emoções intensas e pensamento crítico que escapam ao controle da corporação. Inicialmente, ele tenta ignorar essas sensações, mas não consegue evitar a crescente sensação de que algo está profundamente errado com o mundo em que vive.

Eventualmente, Rai descobre que uma falha nas nanomáquinas implantadas em seu corpo o libertou parcialmente do controle de NeoCorp. Ele começa a recuperar sua liberdade emocional e intelectual, tornando-se um alvo em potencial para as forças de segurança da corporação. Nesse momento de vulnerabilidade, Rai é contatado por Lambda, uma inteligência artificial clandestina que existe fora dos sistemas de controle da NeoCorp. Lambda revela que essa falha é rara, mas crucial, e que Rai pode ser a chave para derrubar a corporação e libertar a humanidade do controle tecnológico.

**Ato II: A Rebelião**
Agora consciente de sua liberdade parcial, Rai é forçado a fugir, pois sabe que, assim que for detectado, a NeoCorp tentará "corrigi-lo" ou neutralizá-lo. Com a ajuda de Lambda, ele começa a explorar áreas esquecidas da cidade, onde pequenos grupos de resistência se escondem, tentando se manter longe do radar da corporação. Ao se unir a esses rebeldes, Rai descobre a extensão do controle que NeoCorp exerce sobre a população e a existência de outros que também escaparam, de forma limitada, das nanomáquinas.

Conforme Rai e Lambda trabalham juntos, ele aprende mais sobre o sistema de monitoramento da NeoCorp e suas vulnerabilidades. A inteligência artificial clandestina revela um plano mais sinistro da corporação: o desenvolvimento de uma nova geração de nanomáquinas, capazes não só de controlar emoções, mas também de apagar memórias e reprogramar completamente as mentes das pessoas. Isso representaria um ponto sem retorno, transformando os cidadãos em verdadeiros autômatos, sem a menor consciência de sua própria identidade ou liberdade.

A urgência da situação força Rai a agir rapidamente. Ele se torna um líder improvisado, conduzindo ataques para expor a verdade sobre a NeoCorp ao público, enquanto busca uma maneira de destruir o núcleo central que controla as nanomáquinas. No entanto, ele enfrenta desafios cada vez maiores, à medida que a corporação intensifica sua caçada por ele, utilizando sua tecnologia para rastrear cada movimento.

**Ato III: A Corrida Contra o Tempo**
No ato final, Rai descobre que a NeoCorp já começou a testar sua nova tecnologia em certas áreas da cidade, reprogramando completamente as mentes de alguns cidadãos para eliminar qualquer vestígio de rebeldia. Ele percebe que sua luta não é mais apenas sobre expor a verdade, mas também sobre impedir que a humanidade perca completamente sua identidade e liberdade. Com o tempo se esgotando, Rai e Lambda lançam um ataque desesperado para destruir a infraestrutura da corporação antes que a nova geração de nanomáquinas seja implantada em massa.

Enquanto Rai enfrenta os perigos de uma sociedade completamente vigiada e controlada, ele também deve lutar contra seus próprios medos. A pressão de salvar não apenas os outros, mas também de evitar que ele próprio seja reprogramado, coloca em risco sua sanidade e determinação. No clímax da história, Rai infiltra-se no centro de controle da NeoCorp, onde a última batalha pela liberdade da humanidade ocorre.

No final, a história deixa uma reflexão sobre os limites entre liberdade e controle, e até onde a tecnologia pode ir para moldar as sociedades humanas. Rai, apesar de vitorioso, descobre que a luta por liberdade nunca realmente termina.
