### ISSUE TITLE
Escrever o roteiro do primeiro capítulo

### ISSUE THREAD

**Issue by juniorbohry** [3ndri0/historia-em-quadrinhos---pt2#3]
Escrever o roteiro do primeiro capítulo, descrevendo como acontece o escape e criar suspense em relação a criação da máquina pela NEOcorp deixando base para criação dos prompts para as primeiras imagens;
Aspectos fundamentais:
Distopia;
Tecnologia extrema;
Dominação;
Regime militarizado;

**Comment by 3ndri0** [comment]
Rai, é aprisionada em um escritório escuro, conectada a um sistema opressivo por cabos de dados, junto com outros cidadãos manipulados pela corporação NEOcorp. Durante um momento de lucidez, ela consegue desativar o cabo que o conecta ao controle da empresa, liberando-se.
Agora livre, Rai precisa escapar da segurança da NeoCorp, que rapidamente se mobiliza para capturá-la. Enquanto isso a corporação está desenvolvendo uma nova geração de máquinas de controle mental;
