### ISSUE TITLE
Buscar Referências para as primeiras imagens

### ISSUE THREAD

**Issue by juniorbohry** [3ndri0/historia-em-quadrinhos---pt2#5]
### **Especificação:**

**Objetivos:** 

- buscar referências para geração das imagens utilizadas no projeto.

**Implementação:**

- Pesquisar na internet imagens de referências sobre cenários e personagens relacionadas ao tema ficção científica.
- Selecionar de 5 a 10 imagens que serão utilizadas para alimentar a IA para gerar o quadrinho do projeto.
- Deve ser selecionada pelo menos duas imagens para personagem do sexo feminino, duas imagens para personagem do sexo masculino e 1 imagem para cenário.
- As imagens selecionadas devem ser livres de direitos autorais.

**Comment by edernatali** [comment]
Imagens selecionadas:

![Image](https://github.com/user-attachments/assets/872348d6-e451-4889-b4cb-063b6a67dfac)
![Image](https://github.com/user-attachments/assets/6ff9e2d7-87ce-465c-b163-1460b7ca2b13)
![Image](https://github.com/user-attachments/assets/72d89233-2d8c-4f37-b65e-583ef79c1900)
![Image](https://github.com/user-attachments/assets/40c588a4-530e-43e6-bd40-31d6de66f046)
![Image](https://github.com/user-attachments/assets/454631c6-3230-44aa-8094-64f5a717fcce)
![Image](https://github.com/user-attachments/assets/59304870-1ba8-4eaf-92f9-ff090fcf0d8e)
![Image](https://github.com/user-attachments/assets/082fdc84-6a09-4e26-9c9c-ffc19ba86a09)
![Image](https://github.com/user-attachments/assets/37d38535-f6e8-4193-9680-75a6bceaf645)
![Image](https://github.com/user-attachments/assets/0b5e270a-65ed-482f-8af1-01abe0072d04)
![Image](https://github.com/user-attachments/assets/9be54f8b-50f1-4991-a3fa-91a727993994)
