### ISSUE TITLE
Gerar imagens para o primeiro capitulo

### ISSUE THREAD

**Issue by juniorbohry** [3ndri0/historia-em-quadrinhos---pt2#6]
Criar prompts com base no roteiro gerado e nas referências;
Aspectos importantes:
4 imagens;
Conexão entre elas;
Encerrar sem desfecho;

**Comment by 3ndri0** [comment]
![Image](https://github.com/user-attachments/assets/6be07dfc-2f73-4fbe-afc5-e24a34428ce9)
![Image](https://github.com/user-attachments/assets/be0fbf55-fbc6-4592-a8ed-e4632bf7ecdb)
![Image](https://github.com/user-attachments/assets/7b45ce50-b55a-4765-8c58-2702e74abf08)
![Image](https://github.com/user-attachments/assets/3073cab9-6e6d-4c8d-8816-aa9191c33400)
