### ISSUE TITLE
Revisão geral

### ISSUE THREAD

**Issue by juniorbohry** [3ndri0/historia-em-quadrinhos---pt2#7]
A revisão final tem como objetivo alinhar e revisar todos os itens, corrigindo erros ortográficos e assegurando que o planejamento estabelecido e os requisitos propostos pela atividade sejam plenamente atendidos.

**Comment by RafaelCapeletti** [comment]
A revisão final tem como objetivo alinhar e revisar todos os itens, assegurando que o planejamento estabelecido e os requisitos propostos pela atividade sejam plenamente atendidos.

**Comment by RafaelCapeletti** [comment]
Foi realizada uma revisão geral com todos os membros do grupo em uma reunião, na qual cada membro apresentou os tópicos cuja execução ficou sob sua responsabilidade, e o grupo discutiu todos os tópicos sem nenhuma alteração.
